name: Build CV and Create Releases

on:
  push:
    tags:
      - 'v-ds-*'
      - 'v-*'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build CV and create release if tagged
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for better tag handling

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Render CV if needed
        run: |
          if [ ! -f "rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf" ]; then
            echo "CV files not found, rendering..."
            uv run rendercv render pradanaadn_CV.yaml
          else
            echo "CV files already exist, skipping render"
          fi

      - name: Extract tag name or use commit info
        id: extract_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # This is a tag push
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
            
            # Convert v-ds-x.x.x to "Data Scientist Version x.x.x"
            if [[ $TAG_NAME == v-ds-* ]]; then
              VERSION=${TAG_NAME#v-ds-}
              TITLE="DS v.$VERSION"
            else
              VERSION=${TAG_NAME#v-}
              TITLE="$VERSION"
            fi
            
            echo "version=$TITLE" >> $GITHUB_OUTPUT
          else
            # This is a branch push or manual trigger
            COMMIT_SHA=${GITHUB_SHA:0:8}
            TAG_NAME="dev-$COMMIT_SHA"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "version=Development Build ($COMMIT_SHA)" >> $GITHUB_OUTPUT
          fi
      - name: Read and sanitize release note
        id: release_note
        run: |
          CV_PATH="rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md"
          if [ -f "$CV_PATH" ]; then
            CONTENT=$(cat "$CV_PATH")
            # Escape newlines and quotes for JSON
            SANITIZED=$(echo "$CONTENT" | jq -Rsa .)
            echo "note=$SANITIZED" >> $GITHUB_OUTPUT
            echo "has_notes=true" >> $GITHUB_OUTPUT
          else
            DEFAULT_NOTE="Release ${TAG_NAME}
            This is an automated release created from tag ${TAG_NAME}."
            SANITIZED=$(echo "$DEFAULT_NOTE" | jq -Rsa .)
            echo "note=$SANITIZED" >> $GITHUB_OUTPUT
            echo "has_notes=false" >> $GITHUB_OUTPUT
          fi
      - name: Verify PDF exists
        id: check_pdf
        run: |
          PDF_PATH="rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf"
          if [ -f "$PDF_PATH" ]; then
            echo "pdf_exists=true" >> $GITHUB_OUTPUT
          else
            echo "pdf_exists=false" >> $GITHUB_OUTPUT
            echo "::warning::PDF file not found at $PDF_PATH"
          fi
      - name: Create release
        if: steps.extract_tag.outputs.is_tag == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read the content directly from file and encode as base64
          NOTES_B64=$(base64 -w 0 rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md)
          
          # Decode and use the content
          gh release create "${{ steps.extract_tag.outputs.tag_name }}" \
            --repo="${GITHUB_REPOSITORY}" \
            --title="${{ steps.extract_tag.outputs.version }}" \
            --notes-file=rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md \
            ./rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf
      
      - name: Upload artifacts for development builds
        if: steps.extract_tag.outputs.is_tag == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: cv-${{ steps.extract_tag.outputs.tag_name }}
          path: |
            rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf
            rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md
            rendercv_output/Putu_Gede_Pradana_Adnyana_CV.html
          retention-days: 30
